services:
  - type: web
    name: propply-nextjs
    env: node
    buildCommand: |
      # Install Node dependencies
      npm install
      # Install Python dependencies
      pip install -r requirements.txt
      # Clear Next.js cache and build fresh
      rm -rf .next
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_SITE_URL
        value: https://propply-nextjs.onrender.com
